name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Run unit tests
      run: make test

    - name: Run integration tests
      run: make test-integration

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: test/reports/
        retention-days: 14

    - name: Build
      run: make build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      if: github.ref == 'refs/heads/main'
      run: make package

    - name: Build Docker image (without push)
      if: github.ref != 'refs/heads/main'
      run: |
        # Enable Docker buildx
        docker buildx create --name cibuilder --use
        # Build for current platform only, without pushing
        docker buildx build --platform linux/amd64 \
          --tag starbops/todoissh:test \
          --load \
          .

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: todoissh-binary
        path: bin/todoissh
        retention-days: 14

    - name: Run security scan
      uses: anchore/scan-action@v3
      with:
        image: starbops/todoissh:${{ github.ref == 'refs/heads/main' && 'latest' || 'test' }}
        fail-build: true
        severity-cutoff: high
