name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Run tests
      run: make test

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: test/reports/
        retention-days: 14

    - name: Build
      run: make build

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: make package

    - name: Upload binary
      uses: actions/upload-artifact@v4
      with:
        name: todoissh-binary
        path: bin/todoissh
        retention-days: 14

    - name: Run security scan
      uses: anchore/scan-action@v3
      with:
        image: todoissh:latest
        fail-build: true
        severity-cutoff: high 